name: SonarQube Front-end

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar-front:
    name: Sonar Front-end
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install sonar-scanner
        run: npm install -g sonar-scanner

      - name: Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=mariem512_fs-oc-p10-front \
            -Dsonar.organization=mariem512 \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://sonarcloud.io
        working-directory: front