name: Tests & Coverage Front-end

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests-front:
    name: Build & Test Front-end
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Launch tests
        run: npm run test:ci

      - name: Coverage tests
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Tests Front-end
          path: front/coverage/bobapp